---
title: "BIOS 617 - Lecture 3"
author: "Walter Dempsey"
date: "1/15/2019"
output:
  beamer_presentation: default
  ioslides_presentation:
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## SRS without replacement

- Generate sample of size $n$ from $N$ by sampling without replacement
- Given $j$ *unique* selected units, the next unit is sampled uniformly at random from remaining $N-j$ units each with probability $1/(N-j)$.
- There are ${N \choose n} = \frac{N!}{n! (N-n)!}$ possible samples
- **Show**: sample mean under SRS is unbiased
- **Show**: sample variance is $(1-f) \frac{S^2}{n}$

## Review of unbiasedness

* What is the probability of sampling individual $j$?
$$\small
\begin{aligned}
P(I_j = 1) &= 1 - P(I_j \neq 1) \\
&= 1 - \frac{N-1}{N} \times \frac{N-2}{N-1} \times \cdots \times \frac{N-n}{N-(n-1)} \\
&= 1 - \frac{N-n}{N} = \frac{n}{N}
\end{aligned}
$$
* What is the probability of both individual $j$ and $i$ being sampled?
$$\small
\begin{aligned}
P(I_k = 1 \text{ and }  I_j = 1) &= P(I_k = 1) \times P(I_j = 1 \, | \, I_k = 1) = \frac{n}{N} \times \frac{n-1}{N-1} \\
\end{aligned}
$$
* What is the probability of $k < n$ specific individuals sampled?
$$
\prod_{j=0}^{k-1} \frac{n-j}{N-j}
$$

## Review of unbiasedness
* Then by linearity of expectations
$$\small
\begin{aligned}
E [ \bar y ] &= E \left[ \frac{1}{n} \sum_j I_j Y_j \right] \\
&= \frac{1}{n} \sum_j E [ I_j  ] Y_j \\
&= \frac{1}{n} \sum_j \frac{n}{N} Y_j \\
&= \bar Y
\end{aligned}
$$

## Variance calculation

Let's use prior class results on variance directly
$$ \small
\begin{aligned}
V(\bar y) &= V \left( n^{-1} \sum_{i=1}^n y_i \right) = \frac{1}{n^2} V \left( \sum_{i=1}^n y_i \right) \\
&= \frac{1}{n^2} \left[ \sum_{i,j=1}^n \text{Cov} (y_i, y_j) \right] \\
&= \frac{1}{n^2} \left[ \sum_{i=1}^n V(y_i) + \sum_{i=1}^n \sum_{j \neq i} \text{Cov} (y_i, y_j) \right] \\
\end{aligned}
$$
We need to better understand $V(y_i)$ and $\text{Cov}(y_i, y_j)$

## Calculate $V(y_i)$

$$
\begin{aligned}
V(y_i) := E[(y_i - \bar Y)^2] &= \sum_{j=1}^N P(\text{select unit $i$}) (Y_i - \bar Y)^2 \\
&= \sum_{j=1}^N \frac{1}{N} (Y_i - \bar Y)^2 \\
&= \frac{N-1}{N} \cdot \frac{1}{N-1} \sum_{j=1}^N (Y_i - \bar Y)^2 \\
&= \frac{N-1}{N} S^2 \\
\end{aligned}
$$

## Covariance manipulations

- For two random variables $X$ and $Z$,
$$
Cov(X, Z ) = E[X \cdot Z] - E[X] E[Z]$$
- Therefore
$$
\frac{N-1}{N} S^2 = V(y_i) = E[y_i^2] - E[y_i]^2 = E[y_i^2] - \bar Y^2
$$
which implies $E[y_i^2] = \bar Y^2 + \frac{N-1}{N} S^2$
- Moreover,
$$
\text{Cov}(y_i, y_j) := E[y_i y_j] - \bar Y^2
$$
- So computation of covariance comes down to computing second moments

## Method 2: Computing moments

$$
\begin{aligned}
E[ y_j \, | \, y_i ] &= \sum_{j \neq i} P(j \text{ selected} \, | \, y_i) Y_j \\
&= \sum_{j \neq i} \frac{1}{N-1} Y_j \\
&= \frac{1}{N-1} \left[ \sum_{j=1}^N Y_j - y_i \right] \\
&= \frac{1}{N-1} \left[ N \bar Y - y_i \right]
\end{aligned}
$$

## Other
$$ \small
\begin{aligned}
E[y_i y_j ] &= E \left[ y_i E [ y_j \, | \, y_i] \right] \\
&= E \left[ \frac{y_i}{N-1} \left( N \bar Y - y_i \right) \right] \\
&= \frac{N \bar Y}{N-1} E \left[ y_i \right] - \frac{1}{N-1} E[ y_i^2 ] \\
&= \frac{1}{N-1} \left( N \bar Y^2 - \bar Y^2 - \frac{N-1}{N} S^2   \right) \\
&= \bar Y^2 - \frac{S^2}{N}
\end{aligned}
$$
So the $\text{Cov} (y_i, y_j) = \bar Y^2 - \frac{S^2}{N} - \bar Y^2 = -\frac{S^2}{N}$

## Put it all together

$$ \small
\begin{aligned}
V(\bar y) &= \frac{1}{n^2} \left[ \sum_{i=1}^n V(y_i) + \sum_{i=1}^n \sum_{j \neq i} \text{Cov} (y_i, y_j) \right] \\
&= \frac{1}{n^2} \left[ \sum_{i=1}^n \frac{N-1}{N} S^2 + \sum_{i=1}^n \sum_{j \neq i} -\frac{S^2}{N} \right] \\
&=\frac{1}{n^2} \left[ n \frac{N-1}{N} S^2 - n \cdot (n-1) \frac{S^2}{N} \right] \\
&=\frac{S^2}{n} \left[ \frac{N-1}{N} - \frac{n-1}{N} \right]\\
&=\frac{S^2}{n} \left[ \frac{N-n}{N} \right] = \frac{S^2}{n} (1-f)
\end{aligned}
$$

## Stratified sampling designs

In many settings, there is information about the population available in the sampling frame that can be used to develop strata.

- Examples
  + Address-based samples: geographic region
  + Telephone numbers: telephone exchanges (region, cell vs. landline)

Basic idea: divide sampling frame into strata, and then sample **within** each stratum

- Why do we do this?
  + Improve efficiency (homogeneity within strata, equalize sample sizes for
subgroups we want to compare).
  + Separate study domains.
  + Implement different sampling strategies within different strata.
  + Administrative convenience.

## Stratified sampling designs: Notation

- Index strata by $h=1,\ldots, H$
- Population size within stratum $h$: $N_h$; $N = \sum_{h=1}^H N_h$.
- Proportion in stratum $h$: $P_h = N_h / N$
- Observation $i \in h$: $Y_{ih}, i = 1,\ldots, N_h$
- Population mean in stratum $h$: $\bar Y_h = N_h^{-1} \sum_{i=1}^{N_h} Y_{ih}$
- Population variance in stratum $h$: $S_h^2 = (N_h-1)^{-1} \sum_{i=1}^{N_h} (Y_{ih}-\bar Y_{h})^2$


## Stratified sampling: Relation to population mean

$$ \small
\begin{aligned}
\bar Y &= N^{-1} \sum_{h=1}^H \sum_{i=1}^{N_h} Y_{ih} \\
 &= \sum_{h=1}^H \frac{N_h}{N} \frac{1}{N_h} \sum_{i=1}^{N_h} Y_{ih} \\
 &= \sum_{h=1}^H P_h \bar Y_h \\
\end{aligned}
$$

## Stratified sampling: Relation to population variance
$$ \small
\begin{aligned}
S^2 &= (N-1)^{-1} \sum_{h=1}^H \sum_{i=1}^{N_h} (Y_{ih} - \bar Y)^2 \\
  &= (N-1)^{-1} \sum_{h=1}^H \sum_{i=1}^{N_h} (Y_{ih} - \bar Y_h + \bar Y_h  - \bar Y)^2 \\
  &= (N-1)^{-1} \sum_{h=1}^H \sum_{i=1}^{N_h} \left[ (Y_{ih} - \bar Y_h)^2 + 2 (Y_{ih} - \bar Y_h) (\bar Y_h  - \bar Y) + (\bar Y_h  - \bar Y)^2  \right] \\
  &= \sum_{h=1}^H \frac{N_h -1}{N-1} \frac{1}{N_h-1}\sum_{i=1}^{N_h} (Y_{ih} - \bar Y_h)^2 +  \sum_{h=1}^H \frac{N_h}{N-1} (\bar Y_h  - \bar Y)^2  \\
  &= \sum_{h=1}^H \frac{N_h -1}{N-1} S_h^2 + \sum_{h=1}^H \frac{N_h}{N-1} (\bar Y_h  - \bar Y)^2  \\
  &\approx \sum_{h=1}^H P_h \left(S_h^2 + (\bar Y_h  - \bar Y)^2 \right)  \\
\end{aligned}
$$

## Sample mean estimator from stratified sample

$$ \small
\bar y_{st} = N^{-1} \sum_h N_h \bar y_h = \sum_h P_h \bar y_h
$$

- Unbiased if estimation of $\bar y_h$ is unbiased (e.g., SRS within each stratum): $E [ \bar y_{st} ] = \sum_h P_h E [ \bar y_h ] = \sum_h P_h \bar Y_h = \bar Y$.
- Since sampling is independent across strata:
$$ \small
V(\bar y_{st}) = \sum_h P_h^2 V(\bar y_h)
$$

- General result; the form of sampling within each stratum determines $V ( \bar y_h )$.
- Unbiased estimators $v ( \bar y_h )$ of $V ( \bar y_h )$ yield an unbiased estimator of the the variance
  + Note that estimation of $V ( \bar y_{st} )$ requires at least two observations per stratum

## SRS within strata

- For SRS with strata, sample mean per strata is $\bar y_h = n_h^{-1} \sum_{i=1}^{n_h} y_{hi}$
- Population estimate is unbiased:
$$ \small
  \bar y_{st} = \frac{1}{N} \sum_h N_h \bar y_h
  = \frac{1}{N} \sum_h \frac{N}{n_h}  \sum_{i=1}^{n_h} y_{hi}
  = \frac{1}{N} \sum_h  \sum_{i=1}^{n_h} w_{hi} y_{hi}
$$

- Variance estimate $v(\bar y_h) = (1-f_h) s_h^2 / n_h$ is unbiased for $V(\bar y_h)$, so
$$ \small
v(\bar y_{st}) = \sum_h P_h^2 \left(1-\frac{n_h}{N_h} \right) \frac{s_h^2}{n_h}
$$
is an unbiased for $V(\bar y_{st})$.

## Proportionate allocation

- Allocation refers to sample sizes $n_1, \ldots, n_H$ with each of the strata
- Porportionate allocation sets $n_1, \ldots, n_H$ so that
$$
\frac{n_1}{N_1} = \frac{n_2}{N_2} = \ldots \frac{n_H}{N_H} = \frac{n}{N}
$$
which is equivalent to $f_h = f$ for all $h=1,\ldots, H$.
- Proportionate allocation thus chooses $n_h = \frac{n}{N} N_h = f N_h$ and thus

$$
\frac{n_h}{n} = \frac{f N_h}{n} = \frac{N_h}{N} = P_h
$$

## Proportionate allocation vs. SRS

- Like SRS, proportionate allocation is an \emph{equal probability selection method}, or \emph{epsem}, design.
- Thus resulting unbiased estimator of the proportionally stratified mean is equal to the SRS estimator of the mean:
$$
\begin{aligned}
\bar y_{st} &= \sum_h P_h \bar y_h = \sum_h \frac{N_h}{N} \left[ \frac{1}{n_h} \sum_{i} y_{hi} \right] \\
&= \sum_h \frac{n_h}{n} \left[ \frac{1}{n_h} \sum_i y_{hi} \right] = \frac{1}{n} \sum_h \sum_i y_{hi} = \bar y
\end{aligned}
$$

## Design effects

- Even though the proportionally stratified mean estimator is equal to the SRS mean estimator, its variance is **NOT** the same:
$$ \small
\begin{aligned}
V(\bar y_{st}) &= \sum_h P_h^2 (1-f_h) S_h^2 / n_h = (1-f) \sum_h \left( \frac{N_h}{N} \right)^2 S^2_h / n_h \\
&= (1-f) \sum_h \left( \frac{N_h}{N} \right) \frac{n_h}{n} S^2_h / n_h  = (1-f) \sum_h P_h S_h^2 / n.
\end{aligned}
$$
- The ratio $V(z)/ V(z_0)$, where $V(z)$ is the variance of a sample statistic $z$ under the true sample design, and $V(z_0)$ is the variance of the sample statistic for a SRS of the same total sample size, is called the _design effect_ (a.k.a. _deff_, $D^2(z)$, or $D^2$)

## Design effects

For large $N_h$, we can show that the deff of proportionate stratified sample is always less than or equal to $1$. Recall,

- $V(\bar y_{st}) = (1-f) \sum_h P_h S_h^2 / n$
- $V(\bar y) = (1-f) S^2 / n$
- $S^2 \dot = \sum_h P_h [ S_h^2 + (\bar Y_h - \bar Y)^2 ]$
$$ \small
\text{deff} = \frac{V(\bar y_{st})}{V(\bar y)} \dot = \frac{\sum_h P_h S_h^2}{\sum_h P_h S_h^2 + \sum_h P_h (\bar Y_h - \bar Y)^2}
$$
- Thus
$$
\text{deff} = \left( 1 + \frac{\sum_h P_h (\bar Y_h - \bar Y)^2}{\sum_h P_h S_h^2}\right)^{-1} \leq 1
$$
- What factors increase the efficiency of proportionate allocation?

## Design effects

If population sizes are small, the increased efficiency is **not** guaranteed:
$$ \small
\begin{aligned}
& V(\bar y_{st}) - V(\bar y) \\
=& \frac{(1-f)}{n} \sum_h P_h S_h^2 - \frac{(1-f)}{(N-1) \cdot n} \left( \sum_{h=1}^H (N_h -1) S_h^2 + \sum_{h=1}^H N_h (\bar Y_h  - \bar Y)^2 \right) \\
=& \frac{(1-f)}{n} \left( \sum_h P_h S_h^2 - \frac{N}{(N-1)}\sum_{h=1}^H P_h S_h^2 - \frac{1}{N-1} \sum_h  \left( N_h (\bar Y_h  - \bar Y)^2 - S_h^2 \right) \right) \\
=& \frac{(1-f)}{n} \left( -\frac{1}{N-1} \sum_h P_h S_h^2 - \frac{1}{N-1} \sum_h  \left( N_h (\bar Y_h  - \bar Y)^2 - S_h^2 \right) \right) \\
=& \frac{(1-f)}{n (N-1)} \left( \sum_h (1-P_h) S_h^2 - \sum_h N_h (\bar Y_h  - \bar Y)^2 \right) < 0
\end{aligned}
$$

## Design effects

- Stratified sampling more efficient when
$$
\sum_h (1-P_h) S_h^2 < \sum_h N_h (\bar Y_h  - \bar Y)^2
$$
- Suppose variances are equal across strata ($S_h \equiv S^2$)
- SRS is more efficient than proportionate allocation when
$$ \small
S^2 \sum_h (1-P_h) > \sum_h N_h (\bar Y_h - \bar Y)^2
$$
$$ \small
\Rightarrow S^2 > (H-1)^{-1} \sum_h N_h (\bar Y_h - \bar Y)^2
$$

## Design effects
- This is equivalent to the F-statistic for the test of the
homogeneity of mean being less that 1:
$$
\begin{aligned}
F &= \frac{\text{between-stratum variability}}{\text{within-stratum variability}} \\
&= \frac{(H-1)^{-1} \sum_h N_h (\bar Y_h - \bar Y)^2 }{S^2} < 1
\end{aligned}
$$

- This is not a true “test statistic” because these quantities are population
values, not random variables. But it does give intuition that stratified
sampling for efficiency requires differential stratum means that reduce
overall sampling variance to a meaningful degree.

## JITT #3

- Show $\bar y_{h}$ under SRS from the strata is unbiased
- Show population estimate $\bar y_{st}$ is unbiased
- What is the difference between stratification sampling and subdomain estimation?


